### ISSUE TITLE
Active Scaffold Export - Difference from older Rails app

### ISSUE THREAD

**Issue by donsisco** [cetani/active_scaffold_export#6]
When testing the Par Level Rule Importer for a recent PR, I noticed that the export differed from the current Temperature/ Hand Hygiene Exporter. I assume this was the old importer for Activate as well.
https://github.com/cetani/Temperature/blob/bda6094b3d0a87d62f956a503ebfa039a99dcb35/vendor/plugins/ewildgoose-active_scaffold_export-0cc43ac/lib/active_scaffold/helpers/export_helpers.rb#L12-L31
https://github.com/cetani/active_scaffold_export/blob/a7845e7ce8718c7ee25813c9f3d5bb4811789eca/lib/active_scaffold/helpers/export_helpers.rb#L12-L28

The main difference here is that the old version was using the list's helper as a fallback if the export helper wasn't defined. 

I think we should at least have that be a configurable option prior to upgrading Temp or HH to a later version of rails. 

The case where I was this was in the Par Level Rules where the Area export was expected to show `"[Entire Map]"` but `"-"` was exported. The importer currently expects to see the `"[Entire Map"` not a blank entry like `"-"`. Thus an export/import will fail. We can fix this in Activate for this case. 

I just think we should add this functionality back, or add a setting to do reuse the list helper.

**Comment by msjonker** [comment]
I don't know that I agree with this. For this case, it seems to make sense, however sometimes the helper will take a value and make it into a more presentable format, sometimes using HTML, changing the date format, etc. The exporter way of doing this is to define a `#{column}_export_column` helper to override the value for the export. If the column and export column helper should be the same, then the column helper can be aliased to `#{column}_export_column`.

**Comment by donsisco** [comment]
We can do that. I'll make an issue in Temp/HH to add the aliases. Which will likely be part of the upgrade.

**Comment by donsisco** [comment]
Closing this issue, see the two tagged issues above for adding aliases to combat this issue on upgrade.
